name: Update Dependency Graph for sbt
on:
  push:
    branches:
      - main
      - sbt-dependency-graph-36d132ea0043bd5d
  workflow_dispatch:
jobs:
  dependency-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        id: checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Install Java
        id: java
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.2.0
        with:
          distribution: corretto
          java-version: 17
      - name: Install sbt
        id: sbt
        uses: sbt/setup-sbt@8a071aa780c993c7a204c785d04d3e8eb64ef272 # v1.1.0

      - name: Submit dependencies for backup-paramater-store
        id: submit-backup-paramater-store
        uses: scalacenter/sbt-dependency-submission@64084844d2b0a9b6c3765f33acde2fbe3f5ae7d3 # v3.1.0
        with:
          working-directory: ./backup-paramater-store

      - name: Submit dependencies for facia-purger
        id: submit-facia-purger
        uses: scalacenter/sbt-dependency-submission@64084844d2b0a9b6c3765f33acde2fbe3f5ae7d3 # v3.1.0
        with:
          working-directory: ./facia-purger

      - name: Log snapshot for backup-paramater-store
        id: validate-backup-paramater-store
        run: cat ${{ steps.submit-backup-paramater-store.outputs.snapshot-json-path }} | jq

      - name: Log snapshot for facia-purger
        id: validate-facia-purger
        run: cat ${{ steps.submit-facia-purger.outputs.snapshot-json-path }} | jq

    permissions:
      contents: write
